### ISSUE TITLE
"import tensorflow.compat.v1 as tf" exits with "Illegal instruction"

### ISSUE THREAD

**Issue by charlie-ht** [microsoft/tensorflow-directml#39]
I'm following the instructions here https://docs.microsoft.com/en-gb/windows/win32/direct3d12/gpu-tensorflow-wsl

```
(directml) cht@DESKTOP-IHJTV93:~$ python
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow.compat.v1 as tf
Illegal instruction
(directml) cht@DESKTOP-IHJTV93:~$
```

This is quite exotic for me, so not sure ahead-of-time what information will help, but here's a start,

OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.20152 N/A Build 20152
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
Linux version 4.19.104
GPU: Nvidia GeForce GTX 1050 Ti

**Comment by jstoecker** [comment]
Quick update: this bug should be fixed in the new [1.15.4-dev201216 release](https://github.com/microsoft/tensorflow-directml/releases/tag/v1.15.4.dev201216). Try it out and let us know how it goes!

**Comment by jglara** [comment]
Hi, I have tried with 1.15.4-dev201216 release in WSL2 and I am still getting the same error:

pip list |grep directml
tensorflow-directml  1.15.4.dev201216

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

cat /proc/version
Linux version 5.4.91-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP Mon Jan 25 18:39:31 UTC 2021

windows OS version:             10.0.21327 N/D Compilación 21327

Processor model name      : Intel64 Family 6 Model 30 Stepping 5 GenuineIntel ~2801 Mhz

**Comment by jstoecker** [comment]
@jglara I believe your CPU may not support AVX, which is a requirement for the packages on pypi. According to [this table](https://en.wikichip.org/wiki/intel/cpuid#Family_6) your CPU appears to be from the Nehalem architecture (likely an i7-720QM from the clock speed you listed), which doesn't have AVX. You can check for AVX support using one of the recommendations [here](https://www.quora.com/How-can-I-determine-if-my-CPU-supports-AVX-instructions); for example, does typing `grep avx /proc/cpuinfo` into your WSL Ubuntu shell print anything? The official tensorflow packages on pypi also require AVX, so another way of checking is trying them (i.e. `pip install tensorflow==1.15`).
